### ISSUE TITLE
After 2 months still does not build!!

### ISSUE THREAD

**Issue by mach37** [VelocityDB/VelocityDB#10]
Hi Mats, I tried today it still did not build its [2 months and still does not build,](https://github.com/VelocityDB/VelocityDB/issues/9) and your versions range from 100 to 400 for a non building software. How do you expect my boss to make a commitment like this if I cant get it going.

_PS:_ 
- I'm doing this on my own time, please seriously consider open mind with **a more realistic and fairer price point developer** version at the 30$ to 50$ price point? till you get this baked in, by now you probably passed up many sales, since MongoDB and others are free with many samples, native drivers and management tools. 
- please include the change event subscription in the developer & client versions.
- in your roadmap please add  GUI management tool upgrade plans
- consider db context filter like soft deletes and tenants, I have to dig up some links that should help you get it.
- time objects like fluent time (on github) are also needed natively on the Db to` enable time series data,` for e.g. get all orders by week, for all weeks in last month.
- while you list FK support, **its not easy to implement nested or reference data navigation like FK**, perhaps annotations with identity, self incrementing, heirachyId, GIS data types and shapes, primary keys and composite type keys need to be called out in easier form, just like the EF convention.
- Let people plan - for e.g. calling out what are the average sizes and limits of a table, _for e.g. what is an average number of records a table can handle easily in velocityDb 1million records each with 1 Kb_? this will help people like my mgr to understand if his current db will fit into this velocity, we have sql express and access right now at 2GB, 3GB, we are pushing Access limits.

hold an open mind 😃 and read again - but from a developers view

Thanks

**Comment by VelocityDB** [comment]
Thanks, I will consider your requests. As for the build, I updated our ReadMe.md file with instructions and it was also added to our User's Guide. Let me know if after installing these prerequisites you still have problems building it?

**Comment by VelocityDB** [comment]
About MongoDB pricing, it is [not FREE](http://siliconangle.com/blog/2014/08/19/mongodb-now-offers-support-for-community-edition-of-its-nosql-database/). 
"The package is priced at $250 per month per production server, or $125 per month for each testing or QA server. That compares nicely with the price of MongoDB Enterprise edition, which comes in two tiers – Core, at $6,500 per year, and Advanced, priced at $10,000 per year."

**Comment by VelocityDB** [comment]
About time objects, we do work with [Noda Time](http://nodatime.org/), is that sufficient?
