### ISSUE TITLE
What is VelocityDBServer?

### ISSUE THREAD

**Issue by rhires** [VelocityDB/VelocityDB#2]
The website doesn't say, except that VelocityGraph not using VelocityDBServer. What does that mean? And what is the difference between VelocityDB and VelocityGraph? I wasn't able to find any definition of these things anywhere.

**Comment by VelocityDB** [comment]
VelocityDBServer is a VelocityDB server that serves VelocityDB/VelocityGraph clients using ServerClientSession sessions. The server mostly serves pages to/from clients but also has additional functionality such as backups to other servers and event notification.

VelocityDB is a .NET object database. VelocityGraph is a .NET property graph database. You can combine them as a hybrid object & graph database. A graph can be used like a collection within VelocityDB. VelocityDB objects can be used as property values within VelocityGraph.
