### ISSUE TITLE
How to persist and compare word documents

### ISSUE THREAD

**Issue by weedkiller** [VelocityDB/VelocityDB#23]
Word documents are a hierarchy of sections, and RDB work but I was thinking VBD might be faster.

Do you have any samples or persisting and comparing hierarchies like 3 word documents. 

What does that VDB model look like?

Interesting issue... 💡

**Comment by VelocityDB** [comment]
Hi,

 

From: weedkiller ***@***.***> 
Sent: Sunday, May 16, 2021 5:30 PM
To: VelocityDB/VelocityDB ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VelocityDB/VelocityDB] How to persist and compare word documents (#23)

 

Word documents are a hierarchy of sections, and RDB work but I was thinking VBD might be faster.

***@***.*** It sure will be.

Do you have any samples or persisting and comparing hierarchies like 3 word documents.

***@***.*** I don’t know what you want to accomplish but my guess is you want something like an inverted index per section, then you can iterate and compare those indexes.

What does that VDB model look like?

***@***.*** It’s much like C# in memory model except in storage an object reference is store as Id + TypeId or if embedded, it stored embedded in the owning object. As examples Arrays and string are stored embedded (usually). You should know that ISerializable classes are stored as the interface API dictates and that is usually not an efficient way. Therefore don’t use classes like HashSet, Dictionary …

You can see exactly the model using DatabaseManager, it shows how your objects are connected and even how schema is connected.

Interesting issue... 💡

**Comment by weedkiller** [comment]
I saw the triangle counter speed, and wanted to try and use VDB engine to compare objects/sections since its a object graph.

Below is some code, using the openXML kit free stuff I can parse out the document, I could use some help and guidance on how to store and compare the graph using VDB

here is the lib [ref](https://github.com/OfficeDev/Open-XML-SDK/blob/main/src/DocumentFormat.OpenXml/Packaging/WordprocessingDocument.cs)

```
public static void ParseSection(string docName, string docToStoreCompare)
    {
        // 2nd doc
        WordprocessingDocument VDBdocToStoreCompare = WordprocessingDocument.Open(docToStoreCompare, true);
        ....
    
        using (WordprocessingDocument document = WordprocessingDocument.Open(docName, true))
        {
            DocumentFormat.OpenXml.Wordprocessing.Document doc = document.MainDocumentPart.Document;

            List<Text> compareTextparts = document.MainDocumentPart.Document.Body.Descendants<DocumentFormat.OpenXml.Wordprocessing.Text>().ToList();
            bool remove = false;
            foreach (Text textfield in compareTextparts )
            {
                
                if (textfield.Text.... )
                {
                   
                }

            }
        }
    }
```

How can I get the VDB to help store and compare..

**Comment by VelocityDB** [comment]
Maybe something like this, WordprocessingDocument probably isn't suitable to store as is, instead I would create each doc on demand as in code here. Created with original context (text) as input.

`using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using VelocityDb;
using VelocityDb.Session;

namespace Weedkiller
{
  class Program
  {
    static void Main(string[] args)
    {
      Console.WriteLine("Hello World!");

      using (var session = new SessionNoServer("Docs"))
      {
        session.BeginUpdate();
        var d = new WordprocessingDocumentPersistent("c:/myDocs/a.docx");
        session.Persist(d);
        session.Commit();
      }

    }

    public static void ParseSection(string docName, string docToStoreCompare)
    {
      // 2nd doc
      WordprocessingDocument VDBdocToStoreCompare = WordprocessingDocument.Open(docToStoreCompare, true);
      //....


      using (WordprocessingDocument document = WordprocessingDocument.Open(docName, true))
      {
        DocumentFormat.OpenXml.Wordprocessing.Document doc = document.MainDocumentPart.Document;

        List<Text> compareTextparts = document.MainDocumentPart.Document.Body.Descendants<DocumentFormat.OpenXml.Wordprocessing.Text>().ToList();
        bool remove = false;
        if (compareTextparts.Count > 1)
        {
          for (int i = 0; i < compareTextparts.Count - 1; i++)
          {
            Text textSectionA = compareTextparts[0];
            Text textSectionB = compareTextparts[1];
            if (SessionBase.DefaultStringComparer.Compare(textSectionA.Text, textSectionB.Text) != 0) // something is different
            {

            }
          }
        }
      }
    }
  }

  public class WordprocessingDocumentPersistent : OptimizedPersistable
  {
    FileContent _docText;

    public WordprocessingDocumentPersistent(string docName)
    {
      byte[] bytes = File.ReadAllBytes(docName);
      _docText = new FileContent(bytes);
    }

    public WordprocessingDocument WordprocessingDocument
    {
      get
      {
        return WordprocessingDocument.FromFlatOpcString(_docText.Utf8String);
      }
    }
  }

  public class FileContent : OptimizedPersistable
  {
    byte[] _bytes;

    public FileContent(byte[] bytes)
    {
      _bytes = bytes;
    }

    public string Utf8String
    {
      get
      {
        return System.Text.Encoding.UTF8.GetString(_bytes);
      }
    }

    public override UInt16 ObjectsPerPage
    {
      get
      {
        return 100;
      }
    }
  }

}
`

**Comment by weedkiller** [comment]
Will try it thanks
