### ISSUE TITLE
use solution package nuget instead of project package nuget

### ISSUE THREAD

**Issue by mdissel** [VelocityDB/VelocityDB#3]
Each project has it's own reference to nuget. resulting in a large commit when a new version of velocitydb is released.

**Comment by VelocityDB** [comment]
As far as I know, libraries can not be solution level package, it has to be added to each project within solution that uses it.

**Comment by mdissel** [comment]
Maybe it's an idea to add the velocitydb to the repository and reference the sample from the local file instead of using the nuget reference. The changes for each checkin are meaningless with all those changed packages.

**Comment by mdissel** [comment]
see this repository, 
https://github.com/ServiceStack/ServiceStack/commit/0de9075125db4d1d9ed4e9e1ac69163f167d8dc5
they also upload the binaries to minimize the changelog.

**Comment by VelocityDB** [comment]
OK, I see that but I prefer to have all references to VelocityDB and VelocityGraph libs use their corresponding NuGet. I think that is a better pattern to use. It is too bad that changeset get large to updating NuGet version but that is a NuGet problem to fix, not really our issue.
