### ISSUE TITLE
rename session.Abort to session.Rollback

### ISSUE THREAD

**Issue by mdissel** [VelocityDB/VelocityDB#4]
Please use the nameconvention already used in other implementations.

and maybe it's even better to create a disposable helper transaction object like this.

```
using (Transaction tran = session.BeginUpdate()){

  tran.Commit()
}
```

when dispose is entered without a commit (due to an exception for example call Abort (Rollback) on the transaction.

**Comment by VelocityDB** [comment]
Good suggestions. I am adding it.
