### ISSUE TITLE
is a licensing file needed with every deployment, encryption

### ISSUE THREAD

**Issue by manualshifter** [VelocityDB/VelocityDB#5]
Hi, looks very interesting when compared to Neo , Mongo and Sql.

Is there a way to encrypt the files/data like windows  bit locker. I want to prevent 3 rd parties from using Reflector to peek inside the data.

 1. Do you have anything like bit locker
 2. Will the data or seed data be shipped inside the dll
 3. Does this support ASP 2.2 Identity and Multi-tenancy
 4. Can I download and test this, can I simply drop it in my solution
    and replace sql server express, will it work right out (What steps
    do I need to follow to make this work)    
 5. Recovery options seem meek, considering that the probability of loosing data with a new tech could be high. What options exist to ensure the data is easily recoverable
 6. Do I need to buy a license for even dev? Your pricing seems to be preventing the growth of your product, will you consider something lesser for a developer.
 7. How can I ensure there no nodes lost/orphaned, or vice versa that circular references dont pop up

thanks

**Comment by VelocityDB** [comment]
1. Yes, we support page level Des encryption. We want to expand and open up encryption options so your input would be appreaciated.
2. You deploy with a single DLL or a few if using VelocityGraph. Databases van be pre created and deployed or can be created on demand. You also need to deploy the license database (4.odb).
3. Yes and we provide the source code for it in this repository. Multi-tenacy is not yet supported but we should be able to add it without too much effort. Or you can help us with it.
4. Yes, it is all available to download from: http://velocitydb.com/Download.aspx
5. API and Database Manager allows you to make backups. With server version you can enable contiguous incremental backup. We also provide API to verify that all data is OK to open.
6. We are generous with discounts when you have multiple developers, especially if you are not from a wealthy company. Just ask in an email to me: Mats@VelocityDB.com
7. You can have circular references, we support that. The session Verify API is there to test that all objects are OK to open with no errors.
