### ISSUE TITLE
Security Roles - Actions

### ISSUE THREAD

**Issue by papyr** [VelocityDB/VelocityDB#6]
Hello, is there a way to add roles dynamically to the controller actions in your ASP Identity version, using a web view. I was looking at your identity sample, it seemed like for security I have to change the code on 

```
[authorize"role", role2... etc] 
Public SomAction() {...}
```

If the Admin can manage the roles and access to the controllers from the Admin view that would be great advantage and selling point. 
optionally - do you also have role access to the classes, since the DB objects are classes

thanks

**Comment by VelocityDB** [comment]
Yes, that should be possible. You have all of the sources available in the download and here on GitHub. Let us know if something isn't working as you expect?

**Comment by papyr** [comment]
Hello again, I was trying this with the ASP identity with groups, I saw the update on the models in your ASP MVC sample. 

BTW Here [is some working sample code](http://bit.ly/2opEWo2) on what I was referring to earlier. However when I port it over, its not working on VDB, after updating my old sandbox version from last year, Velocity no longer compiles.

My goal is 2 fold, besides achieving - management of the users/roles/groups, and `to also do a simple discovery of who is in whose group` - so that we can have features, where they friend or recommend/manage groups, this is a critical problem which traditional DB's need new schemas etc.

Also because you have native POCO's I think this would be a gem of a feature - How can I achieve groups & [filtering](https://github.com/jcachat/EntityFramework.DynamicFilters) - you can easily implement vendors or organizational groups with this

**Comment by VelocityDB** [comment]
Hi again, I just came back from a trip to Sweden so I am still catching up on my email. Can you send the ported code that doesn't build, I can make it build (hopefully). Send to mats.persson@gmail.com
The sample we provide still works, does it not?

**Comment by papyr** [comment]
code links are already here, and actually very simple in two projects.

- Download the github code here
- Download the working sample from the link above (you can add it in the same project or create it as a separate project)
- To add filtering, you can do that from nuget directly, there are 3 good libs, but I think its so way easier inside POCO
- A GUI to set up the options on various objects, like filtering, obeservable etc.

**Comment by VelocityDB** [comment]
I tested our ASP.NET Identity driver with our sample app, there was a build error which I fixed.

Sounds like you want additional features added? I also looked briefly at Asp.Net Core Identity.

**Comment by papyr** [comment]
unlike other db's since this is native C#, one huge advantage thats missed is that the auth/sec filters directly work on the objects. There is no reason they should stop at the middle-ware and cant be projected to the objects in db.

As such, an tenant admin model for multi tenancy would be a good case. I can help you with the ASP GUI, if you roll out the db middle-ware for it.

some examples https://github.com/kriasoft/react-starter-kit , this is a very good one... https://github.com/joeaudette/cloudscribe

If you want a native built in GUI for DB, we can extend [this 4K users ](https://github.com/IdentityServer/IdentityServer4) to support the velocity DB

**Comment by VelocityDB** [comment]
OK, let's do this. The ideas in Cloudscribe looks interesting. How about just adding support for VelocityDB as a storage option to Cloudscribe? If not, shall we base it on ASP.NET Identity or not? I think maybe not as it seams to mostly just complicate stuff when pure object storage is available, right? Setting this up is easy, the hard part is knowing what to create, what features and yes a sample GUI or integrate with something like Cloudscribe? What is your plans for this?

**Comment by VelocityDB** [comment]
No response so closing for now
